# SPDX-FileCopyrightText: 2023 Norbert Melzer <timmelzer@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: commit checks

on:
  pull_request:
  push:

jobs:
  generate_matrix:
    runs-on: ubuntu-22.04
    outputs:
      checks: ${{ steps.gen_checks.outputs.checks }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      - id: gen_checks
        run: |
          set -ex
          yq --version
          checks=$(yq -o j . .pre-commit-config.yaml | jq -c '.repos | map(.hooks | map(.id)) | flatten')
          printf "checks=%s" "$checks" >> $GITHUB_OUTPUT

  run_checks:
    runs-on: ubuntu-22.04
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        check: ${{fromJson(needs.generate_matrix.outputs.checks)}}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: nix profile install --inputs-from . nixpkgs#pre-commit nixpkgs#cargo-audit nixpkgs#cargo-deny
      - name: run ${{ matrix.check }}
        run: |
          pre-commit run ${{ matrix.check }} --all-files --verbose
